---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Install Podman
    - name: module-02
      label: Creating Containers in the Web Console
    - name: module-03
      label: Test Grafana Web Interface (GUI)
    - name: module-04
      label: Podman Container Management
    - name: module-05
      label: Test Grafana Web Interface
tabs:
  - name: ">_ Terminal"
    port: 443
    path: /tty1
    user: root
    host: rhel
