= Podman Container Management

Now you will set up a new Grafana container, but this time, you will do so through the Podman command line interface (CLI). Next, download and start a Podman image for Grafana with this command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman run -d --name=Grafana -p 3000:3000 docker.io/grafana/grafana:latest
----

Explanation of the command you just ran: 
* `+--name=Grafana+` specifies the name of your container. 
* `+-p 3000:3000+` specifies that the container should connect through the host’s port 3000 and the container’s port 3000. 
* `+docker.io/grafana/grafana:latest+` is the URL of the dockerfile that your container is based on. `+Grafana/grafana+` is the name of the image and `+:latest+` indicates that you want the most recent version. This allows Podman to retrieve the correct container.

Finally, run this command to view your containers in Podman:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman ps
----

.Output
The output should look like this, although the Container ID will differ:

[source,text]
----
CONTAINER ID IMAGE                           COMMAND CREATED        STATUS        PORTS                  NAMES 
35079bc79503 docker.io/grafana/grafana:latest        17 seconds ago Up 17 seconds 0.0.0.0:3000->3000/tcp Grafana
----
